language: python

sudo: false
python:
- '3.5'

before_install:
  - pip install flake8

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install coverage

script:
  - flake8 code_share
  - pytest
  - python manage.py makemigrations --noinput

after_success: coverage report