# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, max_length=100000, null=True)),
                ('hash_value', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'CodeShare',
            },
        ),
    ]
